---
- name: Copy jenkins build files
  copy:
    src: "build"
    dest: "{{ jenkins__data_path }}"

- name: Build jenkins JCasC image 
  community.docker.docker_image:
    name: jenkins-jcasc
    build:
      path: "{{ jenkins__data_path }}/build"
    source: build

- name: Create Jenkins data path
  file:
    path: "{{ jenkins__data_path }}/home"
    state: directory
    mode: 0777

- name: Create jenkins container
  docker_container:
    name: "jenkins"
    image: "jenkins-jcasc"
    state: started
    restart: no
    privileged: "true"
    restart_policy : always
    comparisons:
      published_ports: strict
    ports: "{{ jenkins__port_bindings }}"
    volumes:
      - "{{ jenkins__data_path }}/home:/var/jenkins_home:rw"
    env:
      GIT_SSL_NO_VERIFY: "true"
      LDAP__BIND_DN: "{{ ldap__bind_dn }}"
      LDAP__BIND_PASSWORD: "{{ ldap__bind_password }}"
      LDAP__BASE_DN: "{{ ldap__base_dn }}"
      LDAP__SERVER: "ldap://{{ ldap__host }}:{{ ldap__port }}"
    network_mode: bridge
    networks:
      - name: "{{ jenkins__network }}"

