---
- name: Create remote data dir
  ansible.builtin.file:
    path: "{{ gitea__data_path }}"
    state: directory
    mode: 0775

- name: Create gitea container
  docker_container:
    name: "{{ gitea__host }}"
    image: "gitea/gitea:1.22.2"
    state: started
    restart: no
    restart_policy : always
    comparisons:
      published_ports: strict      
    ports: "{{ gitea__port_bindings }}"
    volumes:
      - "{{ gitea__data_path }}:/data"
      - /etc/timezone:/etc/timezone:ro 
      - /etc/localtime:/etc/localtime:ro 
    env:
      # database config/bitnami
      GITEA__database__DB_TYPE: "postgres"
      GITEA__database__HOST: "{{ gitea__db_host }}"
      GITEA__database__NAME: "{{ gitea__db_name }}"
      GITEA__database__USER: "{{ gitea__db_user }}"
      GITEA__database__PASSWD: "{{ gitea__db_password }}"
      # gitea config
      GITEA____RUN_MODE: "{{ gitea__run_mode }}"
      GITEA____APP_NAME: "{{ gitea__app_name }}"
      GITEA__log__LEVEL: "{{ gitea__log_level }}"
      GITEA__security__INSTALL_LOCK: "true"
      GITEA__service__DISABLE_REGISTRATION: "true"
      GITEA__server__SSH_PORT: "{{ gitea__ssh_port }}"
      GITEA__server__SSH_LISTEN_PORT: "22"
      GITEA__server__DOMAIN: "{{ gitea__domain }}"
      GITEA__server__ROOT_URL: "{{ gitea__root_url }}" 
      GITEA__server__SSH_DOMAIN: "{{ gitea__domain }}"
      GITEA__repository__DEFAULT_BRANCH: "master"
    network_mode: bridge
    networks:
      - name: "{{ gitea__network }}"

