---
core__name: "devops"
core__data_path: "/data"
core__network_prefix: "172.16.21"
core__server_internal_addr: "{{ core__network_prefix }}.1"
core__base_domain: "devops-core.local"
core__docker_network: "core-docker-network"

# VPN config
wg__network_name: "wg_core"
wg__server_port: "51820"
wg__data_path: "{{ core__config_path }}/wireguard"
wg__clients:
  client_01: "101"
  client_02: "102"
  client_03: "103"

# SSL config
ssl__base_domain: "{{ core__base_domain }}"
ssl__ca_system_name: "devops_core"
ssl__ca_common_name: "DevOps Core Tools"
ssl__data_path: "{{ core__config_path }}/ssl"

# ldap config
ldap__base_dn: "dc=devops-core,dc=local"
ldap__admin_username: "admin"
ldap__admin_password: "password"

ldap__bind_dn: "cn=bind,{{ ldap__base_dn }}" 
ldap__bind_password: "password" 
ldap__search_base: "ou=users,{{ ldap__base_dn }}"

ldap__config_username: "master"
ldap__config_password: "password"
ldap__config_dn: "cn={{ ldap__config_username }},cn=config"

ldap__default_username: "devops"
ldap__default_password: "password"

ldap__domain: "{{ core__base_domain }}"
ldap__host: "ldap"
ldap__port: "389"
ldap__internal_addr: "{{ ldap__host }}"
ldap__external_addr: "{{ core__server_internal_addr }}"

ldap__external_server_uri: "ldap://{{ ldap__external_addr }}:{{ ldap__port }}"
ldap__internal_server_uri: "ldap://{{ ldap__internal_addr }}:{{ ldap__port }}"

# lam config
lam__master_password: "password"

# postgres config
postgres__host: "postgres"
postgres__user: "postgres_core"
postgres__password: "password"
postgres__binding_addr: "{{ core__server_internal_addr }}"

# pgadmin config
pgadmin__default_email: "devops@devops-core.io"
pgadmin__default_password: "password"

# gitea config
gitea__host: "gitea"
gitea__ssh_port: "222"
gitea__http_port: "3000"

gitea__app_name: "Gitea :: Core DevOps Tools!"

gitea__db_user: "gitea"
gitea__db_password: "password"

gitea__admin_user: "gitea"
gitea__admin_password: "password"
gitea__admin_email: "gitea@devops-core.local"
