---
- name: Install open ssl
  apt: 
    pkg: openssl
    update-cache: no

- name: Create ssl directories
  file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
  loop:
    - "{{ ssl__ca_root_path }}"
    - "{{ ssl__ca_certs_path }}"
