---
ssl_cert_fqdn: "{{ ssl_cert_subdomain_name }}.{{ core_base_domain }}"
ssl_cert_file_name: "{{ ssl_local_ca_certs_path }}/{{ ssl_cert_fqdn }}"
ssl_cert_subject_alt_name:
  - "DNS: {{ ssl_cert_fqdn }}"
ssl_cert_common_name: "{{ ssl_cert_fqdn }}"
ssl_cert_organization_name: "{{ core_common_name }}"
