---
wg_network_prefix: "172.16.20"
wg_network_name: wg_vpn

wg_server_addr: "{{ ansible_host }}"
wg_server_port: 51820
wg_server_intf_name: "{{ wg_network_name }}"
wg_server_internal_addr: "{{ wg_network_prefix }}.1"

wg_client_persistent_keepalive: 25
wg_client_dns: "{{ wg_server_internal_addr }}, 8.8.8.8, 8.8.4.4"
wg_client_allowed_ips: "{{ wg_network_prefix }}.0/24"

wg_data_path: "/data/wireguard"
wg_yaml_path: "{{ wg_data_path }}/{{ wg_network_name }}"
wg_conf_path: "{{ wg_data_path }}/conf"

wg_server_conf_path: "{{ wg_conf_path }}/servers"
wg_server_yaml_file: "{{ wg_yaml_path }}/{{ wg_network_name }}.yaml"
wg_server_conf_file: "{{ wg_server_conf_path }}/{{ wg_network_name }}.conf"

wg_clients:
  home_pc: 2
  mobile: 3

