---
- name: "Create wireguard directory: {{ item }}"
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ wg_yaml_path }}"
    - "{{ wg_conf_path }}"
    - "{{ wg_server_conf_path }}"

- include_tasks : server.yml

- include_tasks : client.yml  
  loop: "{{ wg_clients | dict2items }}"
