---
gitea__db_host: "postgres"
gitea__db_port: "5432"
gitea__db_name: "gitea"
gitea__db_schema: "public"
gitea__db_user: "gitea"
gitea__db_password: "password"

gitea__admin_user: "gitea"
gitea__admin_password: "password"
gitea__admin_email: "gitea@devops-tools.local"

gitea__app_name: "Gitea :: devops-tools!"
gitea__domain: "gitea.devops-tools.local"
gitea__root_url: "https://{{ gitea__domain }}"
gitea__data_path: "/data/gitea"
gitea__network: "devops-tools"
gitea__log_level: "Info" # Trace, Debug, Info, Warn, Error, Fatal
gitea__run_mode: "prod" # dev, prod

gitea__host: "gitea"
gitea__ssh_port: "222"
gitea__http_port: "3000"
gitea__binding_addr: "{{ ansible_host }}"
gitea__port_bindings:
  - "{{ gitea__binding_addr }}:{{ gitea__ssh_port }}:22"
  - "{{ gitea__binding_addr }}:{{ gitea__http_port}}:3000"
 

