---
gitea_db_host: "postgres"
gitea_db_port: "5432"
gitea_db_name: "gitea"
gitea_db_schema: "public"
gitea_db_user: "gitea"
gitea_db_password: "password"
gitea_admin_user: "gitea"
gitea_admin_password: "password"
gitea_admin_email: "gitea@devops-tools.local"
gitea_app_name: "Gitea :: devops-tools! (auto)"
gitea_domain: "gitea.devops-tools.local"
gitea_root_url: "https://gitea.devops-tools.local"
gitea_data_path: "/data/gitea"
 

