---
- name: Install python-dev/psycopg2
  apt: 
    package: 
      - python3-psycopg2
    update_cache: no

- name: Create postgres container
  docker_container:
    name: "{{ postgres__host }}"
    image: "postgres:16.4-alpine"
    state: started
    restart: no
    restart_policy : always
    comparisons:
      published_ports: strict      
    ports: "{{ postgres__port_bindings }}"
    volumes:
      - "{{ postgres__data_path }}:/data/postgres"
    env:
        POSTGRES_DB: "{{ postgres__db }}"
        POSTGRES_USER: "{{ postgres__user }}"
        POSTGRES_PASSWORD: "{{ postgres__password }}"
        PGDATA: "/data/postgres"
    network_mode: bridge
    networks:
      - name: "{{ postgres__network }}"

