---
- name: Install python-dev/psycopg2
  apt: 
    package: 
      - python3-psycopg2
    update_cache: no

- name: Create postgres container
  docker_container:
    name: "postgres"
    image: "postgres:16.4-bullseye"
    state: started
    restart: no
    restart_policy : always
    ports:
      - "5432:5432"
    volumes:
      - "{{ postgres_local_data}}:{{ postgres_data }}"
    env:
        POSTGRES_DB: "{{ postgres_db }}"
        POSTGRES_USER: "{{ postgres_user }}"
        POSTGRES_PASSWORD: "{{ postgres_password }}"
        PGDATA: "{{ postgres_data }}"
    network_mode: bridge
    networks:
      - name: "{{ core_docker_network }}"

- name: "UFW allow Postgres'"
  ufw:
    rule: allow
    port: "5432"
    proto: tcp
    direction: "in"
    comment: "postgres"
    to_ip: "{{ ansible_host }}"
