---
- name: Install python-dev/psycopg2
  apt: 
    package: 
      - python3-psycopg2
    update_cache: no

- name: Create postgres container
  docker_container:
    name: "postgres"
    image: "postgres:16.4-bullseye"
    state: started
    restart: no
    restart_policy : always
    ports:
      - "{{ postgres_port_bind }}:5432"
    volumes:
      - "{{ postgres_data_path }}:/data/postgres"
    env:
        POSTGRES_DB: "{{ postgres_db }}"
        POSTGRES_USER: "{{ postgres_user }}"
        POSTGRES_PASSWORD: "{{ postgres_password }}"
        PGDATA: "/data/postgres"
    network_mode: bridge
    networks:
      - name: "{{ postgres_network }}"

