core_apt_update_cache: yes

core_common_name: DevOps Tools Project
core_system_name: devops-tools
core_base_domain: devops-tools.local 

core_network_prefix: "172.16.20"
core_server_internal_addr: "{{ core_network_prefix }}.1"

core_docker_network: devops-tools

core_remote_data_path: "/data"
