---
- include_tasks: config.yml
  vars:
    nginx_site: "{{ item.nginx_site }}"
    nginx_proxy_pass: "{{ item.nginx_proxy_pass }}"
    nginx_server_name: "{{ item.nginx_server_name }}"
  loop: "{{ nginx_config }}"

- meta: flush_handlers
