---
- name: Create ghcr.io/ldapaccountmanager container
  docker_container:
    name: "lam"
    image: "ghcr.io/ldapaccountmanager/lam:stable"
    state: started
    restart: no
    restart_policy: always
    comparisons:
      published_ports: strict
    ports: "{{ lam__port_bindings }}"
    env:
      LAM_SKIP_PRECONFIGURE: "false"
      LDAP_DOMAIN: "{{ ldap__base_dn }}"
      LDAP_BASE_DN: "{{ ldap__base_dn }}"
      LDAP_USERS_DN: "ou=users,{{ ldap__base_dn }}"
      LDAP_GROUPS_DN: "ou=groups,{{ ldap__base_dn }}"
      LDAP_SERVER: "{{ ldap__internal_server_uri }}"
      LDAP_USER: "cn={{ ldap__admin_username }},{{ ldap__base_dn }}"
      LAM_LANG: "en_US"
      LAM_PASSWORD: "{{ lam__master_password }}"
    network_mode: bridge
    networks:
      - name: "{{ lam__network }}"
