---
postgres_db: "postgres"
postgres_user: "admin"
postgres_password: "password"
postgres_data_path: "/data/postgres"
postgres_addr: "{{ ansible_host }}"

postgres_port: "5432"
postgres_network: "devops-tools"
postgres_port_bind: "{{ postgres_addr }}:{{ postgres_port }}:5432"
