---
ldap__base_dn: "dc=devops-tools,dc=local"
ldap__admin_username: "admin"
ldap__admin_password: "password"
ldap__base: "{{ ldap__base_dn }}"
ldap__bind_dn: "cn=admin,{{ ldap__base_dc }}" 
ldap__bind_password: "password"

ldap__addr: "{{ ansible_host }}"
ldap__server_uri: "ldap://{{ ldap__addr }}:{{ ldap__port }}"

# LAM default port: 80
lam__port_bindings: []
lam__master_password: "password"
lam__profile_password: "password"
lam__organization_name: "LDAP Account Manager Demo"
lam__network: "devops-tools"


