---
ldap_root: "dc=devops-tools,dc=local"
ldap_admin_username: "admin"
ldap_admin_password: "password"
ldap_base: "{{ ldap_root }}"
ldap_bind_dn: "cn=admin,{{ ldap_root }}" 
ldap_bind_password: "password"

lam_password: "password"
lam_admin_password: "password"

lam_organization_name: "LDAP Account Manager Demo"
