---
- name: Shell apt update
  shell: "apt update"
  changed_when: false
  when: core_apt_update_cache

- block:
  
  - name: Get root path
    shell: "realpath {{ playbook_dir }}/.."
    register: core_root_path_register
    delegate_to: localhost
    changed_when: false

  - name: Set core_local_data_path
    set_fact:
      core_local_data_path: "{{ core_root_path_register.stdout }}/data"

  when: core_local_data_path is undefined

- name: Create local data path
  ansible.builtin.file:
    path: "{{ core_local_data_path }}"
    state: directory
  delegate_to: localhost
