---
- name: shell apt update
  shell: "apt update"
  changed_when: false
  when: apt_update_cache

- block:
  
  - name: get root path
    shell: "realpath {{ playbook_dir }}/.."
    register: local_root_path_register
    delegate_to: localhost
    changed_when: false

  - name: set local_data_path
    set_fact:
      local_data_path: "{{ local_root_path_register.stdout }}/data"

  when: local_data_path is undefined

- name: create local data path
  ansible.builtin.file:
    path: "{{ local_data_path }}"
    state: directory
  delegate_to: localhost
