---
jenkins__local_url: http://localhost:8080
jenkins__username: "{{ ldap__default_username }}"
jenkins__secret: "{{ ldap__default_password }}"
jenkins__agents:
  - name: "docker"
    image: "jenkins/jnlp-agent-docker"
    volumes: 
      - "/var/run/docker.sock:/var/run/docker.sock"
  - name: "generic"
    image: "jenkins/agent"


