---
- name: Install ufw
  apt: 
    name: ufw=0.36.2-1
    update_cache: "no"

- name: "Allow SSH on {{ ufw__ssh_address }}:{{ ufw__ssh_port }}" 
  ufw:
    rule: limit
    port: "{{ ufw__ssh_port }}"
    proto: tcp
    comment: SSH
    to_ip: "{{ ufw__ssh_address }}" 

- name: "Deny everything and set state to {{ ufw__state }}"
  ufw:
    state: "{{ ufw__state }}"
    policy: deny
