---
- name: Install wireguard
  apt: 
    package: 
      - wireguard=1.0.20210914-1
      - resolvconf=1.91+nmu1
    update_cache: "no"

# - name: Set default wg_server_external_addr
#   set_fact:
#     wg_server_external_addr: "{{ ansible_host }}"
#   when: wg_server_external_addr is undefined
