---
- name: Create remote data dir
  ansible.builtin.file:
    path: "{{ pgadmin__data_path }}"
    state: directory
    mode: 0775

- name: Create dpage/pgadmin4 container
  docker_container:
    name: "pgadmin"
    image: "dpage/pgadmin4"
    state: started
    restart: no
    restart_policy : always
    comparisons:
      published_ports: strict      
    ports: "{{ pgadmin__port_bindings }}"
    volumes:
      - "{{ pgadmin__data_path }}:/var/lib/pgadmin:rw"  
    env:
      PGADMIN_DEFAULT_EMAIL: "{{ pgadmin__default_email }}"
      PGADMIN_DEFAULT_PASSWORD: "{{ pgadmin__default_password }}"
    network_mode: bridge
    networks:
      - name: "{{ pgadmin__network }}"
