---  
- name: Create remote ssl certs directories
  file:
    path: "{{ ssl_remote_certs_path }}"
    state: directory

- name: Copy certificates sudo
  copy:
    src: "{{ item }}"
    dest: "{{ ssl_remote_certs_path }}"
  loop:
    - "{{ ssl_cert_file_name }}.key"
    - "{{ ssl_cert_file_name }}.crt"
