---  
- name: Create remote ssl certs directories
  file:
    path: "{{ ssl__remote_certs_path }}"
    state: directory

- name: Copy certificates
  copy:
    src: "{{ item }}"
    dest: "{{ ssl__remote_certs_path }}"
  loop:
    - "{{ ssl__cert_file_name }}.key"
    - "{{ ssl__cert_file_name }}.crt"
