---  
- name: Generate host private key
  openssl_privatekey:
    path: "{{ ssl__cert_file_name }}.key"
    mode: 0775

- name: Generate host CSR
  openssl_csr:
    path: "{{ ssl__cert_file_name }}.csr"
    privatekey_path: "{{ ssl__cert_file_name }}.key"
    common_name: "{{ ssl__cert_common_name }}"
    organization_name: "{{ ssl__cert_organization_name }}"
    subject_alt_name: "{{ ssl__cert_subject_alt_name }}"

- name: Generate host certificate
  openssl_certificate:
    path: "{{ ssl__cert_file_name }}.crt"
    csr_path: "{{ ssl__cert_file_name }}.csr"
    ownca_path: "{{ ssl__ca_pub_key }}"
    ownca_privatekey_path: "{{ ssl__ca_pvt_key }}"
    provider: ownca
    mode: 0775
