---
- name: DevOps Tools Setup
  hosts: server
  become: true
  gather_facts: no
  roles:
    - role: core/server
      tags: core_server
    - role: core/ldap
      tags: core_ldap
    - role: core/database
      tags: core_database
    - role: core/gitea
      tags: core_gitea

    - role: docker/nginx/up
      tags: nginx

    - role: ssl/copy
      tags: nginx, ssl,ssl_certs
      ssl_cert_subdomain_name: _
      ssl_cert_common_name: "*.{{ core_base_domain }}"   

    - role: docker/nginx/config
      tags: nginx, nginx_config
      nginx_config:
        - nginx_site: ldap
          nginx_proxy_pass: http://lam/
          nginx_server_name: "ldap.{{ core_base_domain }}"
        - nginx_site: pgadmin
          nginx_proxy_pass: http://pgadmin/
          nginx_server_name: "pgadmin.{{ core_base_domain }}"
        - nginx_site: "gitea"
          nginx_proxy_pass: http://gitea:3000/
          nginx_server_name: "gitea.{{ core_base_domain }}"
