---
- name: DevOps Tools Setup
  hosts: server
  become: true
  gather_facts: no
  roles:
    - role: core/server
      tags: core_server
    - role: core/ldap
      tags: core_ldap
    - role: core/database
      tags: core_database
    - role: core/gitea
      tags: core_gitea
    - role: core/nginx
      tags: core_nginx
      nginx_config:
        - nginx_site: ldap
          nginx_proxy_pass: http://lam/
        - nginx_site: pgadmin
          nginx_proxy_pass: http://pgadmin/
        - nginx_site: "gitea"
          nginx_proxy_pass: http://gitea:3000/
