---
- name: DevOps Core Tools
  hosts: server
  become: true
  gather_facts: no

  roles:
    - role: core/server
      tags: core_server
    - role: core/ldap
      tags: core_ldap
    - role: core/database
      tags: core_database
    - role: core/gitea
      tags: core_gitea
    - role: core/nginx
      tags: core_nginx
