---
- name: DevOps Tools Setup
  hosts: server
  become: true
  gather_facts: no
  roles:
    # -role: core/common
    - role: core/base_server
    
    # - role: wireguard/server 
    #   tags: vpn     
    # - role: setup/bind9
    #   tags: dns_server
    #   bind9_server_addr: "{{ core.server_internal_addr }}"

    # - role: docker/nginx/up
    #   tags: nginx

    # # ldap tools
    # - role: docker/ldap
    #   tags: ldap
    # - role: docker/lam
    #   tags: [ ldap, lam ]

    # # database tools
    # - role: docker/postgres
    #   tags: postgres
    # - role: docker/pgadmin
    #   tags: pgadmin

    # - role: ssl/copy
    #   ssl_cert_subdomain_name: _
    #   ssl_cert_common_name: "*.devops.auriema.net"    

    # # # install gitea
    # # - role: postgres/add_db
    # #   tags: gitea
    # #   pg_db_name: "gitea"
    # #   pg_db_user: "gitea"
    # #   pg_db_password: "password"
    # #   pg_login_host: "{{ ansible_host }}"
    # #   pg_login_user: "admin"
    # #   pg_login_password: "password"      
    # # - role: docker/gitea
    # #   tags: [ gitea, gitea_install ] 

    # - role: docker/nginx/config
    #   tags: [ nginx, nginx_config ]
    #   nginx_config:
    #     - nginx_site: ldap
    #       nginx_proxy_pass: http://lam/
    #       nginx_server_name: ldap.devops-tools.local
    #     - nginx_site: pgadmin
    #       nginx_proxy_pass: http://pgadmin/
    #       nginx_server_name: pgadmin.devops-tools.local
    #     # - nginx_site: "gitea"
    #     #   nginx_proxy_pass: http://gitea:3000/
    #     #   nginx_server_name: gitea.devops-tools.local

    # # - role: docker/gitea_config
    # #   tags: [ gitea, gitea_config ]
