---
- name: DevOps Tools Setup
  hosts: localhost  
  become: true
  gather_facts: no
  roles:
    # generate wireguard config  
    - role: wireguard/init
    - role: wireguard/config
      wg_clients:
        home_pc: 2
        mobile: 3
