---
- name: Enable ipv4 forwarding
  replace:
    path: /etc/sysctl.conf
    regexp: '^#net.ipv4.ip_forward=1'
    replace: 'net.ipv4.ip_forward=1'
    backup: no
  register: wg__ipv4fw_reg

- name: Restart sysctl
  command: sysctl -p /etc/sysctl.conf 
  when: wg__ipv4fw_reg.changed

- name: Copy config file
  copy:
    src: "{{ wg__server_conf_file }}"
    dest: "/etc/wireguard"
  register: wg__copy_reg   

- name: Start service
  service:
    state: started
    name: "wg-quick@{{ wg__network_name }}"
    enabled: true
  register: wg__start_reg

- name: Restart service
  service:
    state: restarted
    name: "wg-quick@{{ wg__network_name }}"
    enabled: true
  when: wg__copy_reg.changed and not wg__start_reg.changed

- name: "UFW allow wireguard'"
  ufw:
    rule: "limit"
    port: "{{ wg__server_port }}"
    proto: udp
    direction: "in"
    comment: "WG/{{ wg__network_name}}"
    to_ip: "{{ wg__server_addr }}"
  when: core__ufw | default(true)
