---
- name: install wireguard
  apt: 
    package: 
      - wireguard=1.0.20210914-1
      - resolvconf=1.91+nmu1
    update_cache: "no"

- name: Enable ipv4 forwarding
  replace:
    path: /etc/sysctl.conf
    regexp: '^#net.ipv4.ip_forward=1'
    replace: 'net.ipv4.ip_forward=1'
    backup: no
  register: wg_ipv4fw_info

- name: Restart sysctl
  command: sysctl -p /etc/sysctl.conf 
  when: wg_ipv4fw_info.changed

- name: copy config file
  copy:
    src: "{{ wg_server_conf_file }}"
    dest: "{{ wg_remote_config_path }}/{{ wg_network_name }}.conf"
  register: wg_copy_info   

- name: start service
  systemd:
    state: started
    name: "wg-quick@{{ wg_network_name }}"
    enabled: true
  register: wg_start_info  

- name: restart service
  systemd:
    state: restarted
    name: "wg-quick@{{ wg_network_name }}"
    enabled: true
  when: wg_copy_info.changed and not wg_start_info.changed

- name: "UFW allow wireguard'"
  ufw:
    rule: "limit"
    port: "{{ wg_server_port }}"
    proto: udp
    direction: "in"
    comment: "WG/{{ wg_network_name}}"
    to_ip: "{{ ansible_host }}"
