---
- name: Enable ipv4 forwarding
  replace:
    path: /etc/sysctl.conf
    regexp: '^#net.ipv4.ip_forward=1'
    replace: 'net.ipv4.ip_forward=1'
    backup: no
  register: wg_ipv4fw_info

- name: Restart sysctl
  command: sysctl -p /etc/sysctl.conf 
  when: wg_ipv4fw_info.changed

- name: Copy config file
  copy:
    src: "{{ wg_server_conf_file }}"
    dest: "{{ wg_remote_conf_path }}"
  register: wg_copy_info   

- name: Start service
  systemd:
    state: started
    name: "wg-quick@{{ wg_network_name }}"
    enabled: true
  register: wg_start_info  

- name: Restart service
  systemd:
    state: restarted
    name: "wg-quick@{{ wg_network_name }}"
    enabled: true
  when: wg_copy_info.changed and not wg_start_info.changed

- name: "UFW allow wireguard'"
  ufw:
    rule: "limit"
    port: "{{ wg_server_port }}"
    proto: udp
    direction: "in"
    comment: "WG/{{ wg_network_name}}"
    to_ip: "{{ ansible_host }}"
