---
- name: Create docker network
  docker_network:
    name: "{{ nginx_network }}"

- name: Create nginx container
  docker_container:
    name: "nginx"
    image: "nginx:1.23-alpine-slim"
    state: started
    restart: no
    restart_policy : always
    ports:
    - "{{ nginx_http_port_bind }}:80"
    - "{{ nginx_https_port_bind }}:443"
    volumes:
      - "{{ nginx_data_path }}/templates:/etc/nginx/templates"
      - "{{ nginx_data_path }}/conf.d:/etc/nginx/conf.d"
      - "{{ nginx_data_path }}/sites:/var/www/"
      - "{{ nginx_certs_path }}:/data/ssl/certs/"
    network_mode: bridge
    networks:
      - name: "{{ nginx_network }}"

# - name: "UFW allow NGINX http"
#   ufw:
#     rule: deny
#     port: "80"
#     proto: tcp
#     to_ip: "{{ nginx_server_addr }}" 
#     comment: NGINX/http

# - name: "UFW allow NGINX https"
#   ufw:
#     rule: deny
#     port: "443"
#     proto: tcp
#     to_ip: "{{ nginx_server_addr }}" 
#     comment: NGINX/https
