---
- name: Create docker network
  docker_network:
    name: "{{ nginx_network }}"

- name: Create nginx container
  docker_container:
    name: "nginx"
    image: "nginx:1.23-alpine-slim"
    state: started
    restart: no
    restart_policy : always
    ports:
    - "{{ nginx_http_port_bind }}:80"
    - "{{ nginx_https_port_bind }}:443"
    volumes:
      - "{{ nginx_data_path }}/templates:/etc/nginx/templates"
      - "{{ nginx_data_path }}/conf.d:/etc/nginx/conf.d"
      - "{{ nginx_data_path }}/www:/var/www/"
      - "{{ nginx_certs_path }}:/data/ssl/certs/"
    network_mode: bridge
    networks:
      - name: "{{ nginx_network }}"

- name: Create ping directory
  file:
    path: "{{ nginx_sites_path }}/ping"
    state: directory

- name: Copy ping file
  copy:
    src: "ping.html"
    dest: "{{ nginx_sites_path }}/ping/index.html"
  notify: "docker/nginx/restart"

- import_role: 
    name: docker/nginx/config
    tasks_from: config.yml
  vars:
    nginx_site: "ping"
    nginx_template: "site_https"
    nginx_server_name: "ping.devops-tools.local"

- import_role: 
    name: docker/nginx/config
    tasks_from: config.yml
  vars:
    nginx_site: "deny_all_https"
    nginx_template: "deny_all_https"
    nginx_server_name: "_.devops-tools.local"

- import_role: 
    name: docker/nginx/config
    tasks_from: config.yml
  vars:
    nginx_site: "redirect_httpx"
    nginx_template: "redirect_httpx"
    nginx_server_name: "_.devops-tools.local"
