---
- name: set jenkins agent command
  set_fact:
    jenkins__agent_cmd: >-
      'curl -sO -k {{ jenkins__url }}/jnlpJars/agent.jar &&
      java -jar agent.jar -url {{ jenkins__url }} -secret {{ jenkins__agent_secret }} -name {{ jenkins__agent_name }} -workDir {{ jenkins__agent_path }}'

- name: Create jenkins agent docker container
  docker_container:
    name: "jenkins-agent-{{ jenkins__agent_name }}"
    image: "{{ jenkins__agent_image }}"
    state: started
    restart: no
    user: root
    privileged: "true"
    restart_policy : always
    entrypoint: ["/bin/sh", "-c" ]
    command: "{{ jenkins__agent_cmd }}"
    volumes: "{{ jenkins__agent_volumes }}"
    network_mode: bridge
    networks:
      - name: "{{ jenkins__network }}"
