---
- name: Set gitea config commands
  set_fact:
    gitea__user_exists: "/bin/bash -c \"gitea admin user list | awk -F' ' '{ print $2 }' | grep -E ^{{ gitea__admin_user }}$\""
    gitea__add_user_cmd: > 
      gitea admin user create 
      --username {{ gitea__admin_user }} 
      --password {{ gitea__admin_password }} 
      --email {{ gitea__admin_email }} 
      --admin -c /data/gitea/conf/app.ini
    gitea__auth_exists: "/bin/bash -c \"gitea admin auth list |  awk -F' ' '{ print $2 }' | grep -E ^ldap$\""
    gitea__add_ldap: > 
      gitea admin auth add-ldap 
      --name ldap 
      --security-protocol {{ gitea__ldap_security_protocol }} 
      --host {{ gitea__ldap_host }} 
      --port {{ gitea__ldap_port }}
      --user-search-base '{{ gitea__ldap_search_base }}' 
      --user-filter '(&(objectClass=posixAccount)(uid=%s))' 
      --admin-filter '(memberof=cn=admin,ou=groups,{{ ldap__base_dn }})' 
      --email-attribute mail 
      --bind-dn {{ gitea__ldap_bind_dn }} 
      --bind-password {{ gitea__ldap_bind_password }}
      --skip-tls-verify 

- name: "Wait for gitea container to start"
  community.docker.docker_container_exec:
    container: gitea
    command: "curl 127.0.0.1:3000"
  changed_when: false
  register: gitea__result
  until: gitea__result.rc == 0
  retries: 120
  delay: 5

- name: "Check if gitea user exists"
  community.docker.docker_container_exec:
    container: gitea
    user: git
    command: "{{ gitea__user_exists }}"
  register: gitea__user_exists_result
  ignore_errors: true
  changed_when: false

- name: "Add gitea admin user"
  community.docker.docker_container_exec:
    container: gitea
    user: git
    command: "{{ gitea__add_user_cmd }}"
  when: gitea__user_exists_result.rc == 1

- name: "Check if LDAP config exists"
  community.docker.docker_container_exec:
    container: gitea
    user: git
    command: "{{ gitea__auth_exists }}"
  register: gitea__auth_exists_result
  ignore_errors: true
  changed_when: false

- name: "Add LDAP config"
  community.docker.docker_container_exec:
    container: gitea
    user: git
    command: "{{ gitea__add_ldap }}"
  when: gitea__auth_exists_result.rc == 1
